const C=window.STAC_CONFIG||{},$=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let sb=null,user=null,streamers=[],videos=[];
if(C.SUPABASE_URL&&C.SUPABASE_PUBLISHABLE_KEY)sb=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY);
const email=id=>id.toLowerCase()+"@stac.local";
function msg(t){$("#authMessage").textContent=t||""} function addmsg(t){$("#addStreamerMessage").textContent=t||""}
async function login(){const id=$("#authId").value.trim(),pw=$("#authPassword").value;if(!id||!pw)return msg("IDとパスワードを入力してください。");try{let r=await sb.auth.signInWithPassword({email:email(id),password:pw});if(r.error)throw r.error;user=r.data.user;start()}catch(e){msg("ログインできませんでした。")}}
async function signup(){const id=$("#authId").value.trim(),pw=$("#authPassword").value;if(!/^[\w-]{3,24}$/.test(id)||pw.length<6)return msg("IDは3文字以上、パスワードは6文字以上で入力してください。");try{let r=await sb.auth.signUp({email:email(id),password:pw,data:{username:id}});if(r.error)throw r.error;user=r.data.user;start()}catch(e){msg(e.message||"登録できませんでした。")}}
async function start(){$("#authScreen").classList.add("hidden");$("#app").classList.remove("hidden");let n=user.user_metadata?.username||user.email.split("@")[0];$("#userName").textContent=n;$("#userMark").textContent=n[0].toUpperCase();$("#settingsUserId").textContent=n;await loadStreamers();await loadVideos()}
async function loadStreamers(){let r=await sb.from("user_streamers").select("streamer_id,enabled,streamers(id,name,channel_id,thumbnail,enabled)").eq("user_id",user.id).eq("enabled",true);if(r.error)return console.error(r.error);streamers=(r.data||[]).map(x=>x.streamers).filter(Boolean);renderStreamers()}
async function loadVideos(){if(!streamers.length){videos=[];render();return}let ids=streamers.map(x=>x.id);let r=await sb.from("videos").select("*").in("streamer_id",ids).order("published_at",{ascending:false}).limit(300);if(r.error)return console.error(r.error);videos=r.data||[];render();$("#lastSync").textContent="最終確認 "+new Date().toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"})}
function renderStreamers(){let e=$("#myStreamers");if(!streamers.length){e.innerHTML='<div class="empty">まだ登録されていません。</div>';return}e.innerHTML=streamers.map(s=>`<div class="streamer"><div class="streamer-main"><div class="avatar">${s.thumbnail?`<img src="${esc(s.thumbnail)}">`:""}</div><b>${esc(s.name)}</b></div><button class="del" data-del="${esc(s.id)}">削除</button></div>`).join("");e.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>removeStreamer(b.dataset.del))}
async function removeStreamer(id){let r=await sb.from("user_streamers").delete().eq("user_id",user.id).eq("streamer_id",id);if(r.error)return addmsg(r.error.message);await loadStreamers();await loadVideos()}
function render(){let live=videos.filter(v=>v.status==="live"),up=videos.filter(v=>v.status==="upcoming").sort((a,b)=>new Date(a.scheduled_at)-new Date(b.scheduled_at)),latest=videos.filter(v=>v.status==="video"||v.status==="archive").sort((a,b)=>new Date(b.published_at)-new Date(a.published_at));const card=v=>`<article class="card" data-url="${esc(v.url)}"><div class="thumb" style="background-image:url('${esc(v.thumbnail||"")}')"><span class="badge">LIVE NOW</span></div><div class="body"><div class="sub">${esc(v.streamer_name)}</div><div class="title">${esc(v.title)}</div></div></article>`;const row=v=>`<article class="row" data-url="${esc(v.url)}"><div class="time">${new Date(v.scheduled_at).toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"})}</div><div><div class="sub">${esc(v.streamer_name)}</div><div class="title">${esc(v.title)}</div></div><div class="arrow">→</div></article>`;const item=v=>`<article class="row" data-url="${esc(v.url)}"><div class="latest-thumb">${v.thumbnail?`<img src="${esc(v.thumbnail)}">`:""}</div><div><div class="sub">${esc(v.streamer_name)}</div><div class="title">${esc(v.title)}</div></div></article>`;put("#liveList",live,card);put("#livePageList",live,card);put("#upcomingList",up,row);put("#upcomingPageList",up,row);put("#latestList",latest.slice(0,8),item);put("#latestPageList",latest,item)}
function put(sel,arr,fn){let e=$(sel);e.innerHTML=arr.length?arr.map(fn).join(""):'<div class="empty">表示するものがありません。</div>';e.querySelectorAll("[data-url]").forEach(x=>x.onclick=()=>window.open(x.dataset.url,"_blank","noopener,noreferrer"))}
function view(v){document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id===v+"View"));document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===v))}
async function addStreamer(){let input=$("#streamerUrl").value.trim();if(!input)return addmsg("URLまたは@ハンドルを入力してください。");try{let s=await sb.auth.getSession();let r=await fetch(C.ADD_STREAMER_FUNCTION_URL,{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+s.data.session.access_token},body:JSON.stringify({url:input})});let t=await r.text(),d={};try{d=JSON.parse(t)}catch{}if(!r.ok)throw new Error(d.error||t);$("#streamerUrl").value="";addmsg((d.name||"ストリーマー")+" を追加しました。");await loadStreamers();await loadVideos()}catch(e){addmsg("追加できませんでした："+e.message)}}
document.querySelectorAll("[data-view]").forEach(x=>x.onclick=()=>view(x.dataset.view));$("#loginButton").onclick=login;$("#signupButton").onclick=signup;$("#addStreamerButton").onclick=addStreamer;$("#streamerUrl").onkeydown=e=>e.key==="Enter"&&addStreamer();$("#logoutButton").onclick=()=>sb.auth.signOut().then(()=>location.reload());$("#sidebarToggle").onclick=()=>$("#sidebar").classList.toggle("collapsed");$("#mobileMenu").onclick=()=>$("#sidebar").classList.toggle("mobile-open");
(async()=>{if(!sb)return;if((await sb.auth.getSession()).data.session){user=(await sb.auth.getUser()).data.user;start()}})();setInterval(()=>user&&loadVideos(),60000);
