window.STAC_CONFIG = {
  SUPABASE_URL: "PASTE_YOUR_SUPABASE_URL",
  SUPABASE_PUBLISHABLE_KEY: "PASTE_YOUR_SUPABASE_PUBLISHABLE_KEY",
  ADD_STREAMER_FUNCTION_URL: "PASTE_YOUR_ADD_STREAMER_FUNCTION_URL"
};
